# Generated by Django 2.2.9 on 2019-12-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='save',
        ),
    ]
