# Generated by Django 2.2.9 on 2019-12-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_planets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planetss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Planets',
        ),
    ]
